services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql

    pgsql:
        image: postgres:17
        container_name: laravel-pgsql
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: sail
            POSTGRES_PASSWORD: password
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-pgsql:
        driver: local
